import { expect, test } from "./fixtures.js";
import { mkdir, readFile } from "node:fs/promises";
import { PDFDocument } from "pdf-lib";

test("공통 답안지 PDF와 판독 초안 검토·정답 변경·파일 복원", async ({ page }) => {
  test.setTimeout(120000);
  await page.route("https://fonts.googleapis.com/**", (route) => route.abort());
  await page.goto("/", { waitUntil: "domcontentloaded" });
  await page.getByRole("tab", { name: "선생님", exact: true }).click();
  await page.getByLabel("선생님 아이디").fill("preview");
  await page.getByLabel("선생님 비밀번호").fill("preview");
  await page.getByRole("button", { name: "선생님 로그인" }).click();
  await page.getByRole("navigation", { name: "주요 화면" }).getByRole("button", { name: /시험지관리/ }).click();
  await page.getByRole("tab", { name: "채점 실험", exact: true }).click();
  const panel = page.getByRole("region", { name: "채점 실험", exact: true });
  page.on("dialog", (dialog) => dialog.accept());
  const downloadPromise = page.waitForEvent("download");
  await panel.getByRole("button", { name: "공통 답안지 PDF", exact: true }).click();
  const download = await downloadPromise;
  await mkdir("tmp/pdfs", { recursive: true });
  await download.saveAs("tmp/pdfs/answer-sheet.pdf");
  const pdfBytes = await readFile("tmp/pdfs/answer-sheet.pdf");
  const pdf = await PDFDocument.load(pdfBytes);
  expect(pdf.getPageCount()).toBe(1);
  expect(pdf.getPage(0).getWidth()).toBeCloseTo(595.28);
  await panel.getByLabel("정답지 올리기", { exact: true }).setInputFiles({ name: "정답지.pdf", mimeType: "application/pdf", buffer: pdfBytes });
  await expect(panel.getByAltText("선택한 답안 전체 원본")).toBeVisible();
  let calls = 0;
  await page.route("**/api/answer-sheet-pilot/recognize", async (route) => {
    calls++;
    expect(route.request().postDataJSON().paidConsent).toBe(true);
    await route.fulfill({ json: { ok: true, provider: "fixture", rows: Array.from({ length: 20 }, (_, i) => ({ no: i + 1, answer: i === 0 ? "3" : i === 1 ? "1/2" : "", reviewed: false })) } });
  });
  expect(calls).toBe(0);
  await panel.getByRole("button", { name: "선택한 답안 AI 판독 (유료)", exact: true }).click();
  await expect(panel.getByLabel("정답 1번", { exact: true })).toHaveValue("3");
  expect(calls).toBe(1);
  await panel.getByRole("button", { name: "정답 확정", exact: true }).click();
  await expect(panel.getByText("정답 확정됨", { exact: true })).toBeVisible();
  await panel.getByLabel("학생 답안 올리기", { exact: true }).setInputFiles({ name: "학생.pdf", mimeType: "application/pdf", buffer: pdfBytes });
  await expect(panel.getByLabel("학생 답 1번", { exact: true })).toBeVisible();
  await panel.getByLabel("학생 답 1번", { exact: true }).fill("3");
  await panel.getByLabel("학생 답 2번", { exact: true }).fill("0.5");
  await expect(panel.getByRole("status")).toContainText("확인 필요 2");
  await panel.getByLabel("학생 답 1번 원본 확인", { exact: true }).check();
  await panel.getByLabel("학생 답 2번 원본 확인", { exact: true }).check();
  await expect(panel.getByRole("status")).toContainText("정답 1 · 오답 1");
  await panel.getByLabel("분수·소수의 같은 값 허용").check();
  await expect(panel.getByText("정답 미확정").first()).toBeVisible();
  await panel.getByRole("button", { name: "정답지 확인", exact: true }).click();
  await panel.getByRole("button", { name: "정답 확정", exact: true }).click();
  await panel.getByRole("button", { name: "학생 답안 확인", exact: true }).click();
  await expect(panel.getByRole("status")).toContainText("정답 2 · 오답 0");
  await panel.getByLabel("학생 답 1번", { exact: true }).fill("4");
  await expect(panel.getByLabel("학생 답 1번 원본 확인", { exact: true })).not.toBeChecked();
  const exportPromise = page.waitForEvent("download");
  await panel.getByRole("button", { name: "실험 파일 내려받기", exact: true }).click();
  const exported = await exportPromise;
  await exported.saveAs("tmp/pdfs/pilot.json");
  await panel.getByLabel("학생 답 1번", { exact: true }).fill("5");
  await panel.getByLabel("실험 파일 다시 열기", { exact: true }).setInputFiles("tmp/pdfs/pilot.json");
  await panel.getByRole("button", { name: "학생 답안 확인", exact: true }).click();
  await expect(panel.getByLabel("학생 답 1번", { exact: true })).toHaveValue("4");
  await page.screenshot({ path: "tmp/pdfs/pilot-screen.png", fullPage: true });
  expect(await panel.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
});
