import { normalizeExamOutputLayoutChoices } from "./finalDocument.js";
import { createExamAnalysisFolderId } from "./library.js";

const defaultAcademyBrandName = "으뜸수학 고태영T";

export function createDefaultExamAnalysisPrompt(options = {}) {
  const academyBrandName = options.academyBrandName || defaultAcademyBrandName;
  return [
    `역할: ${academyBrandName}의 학교별 내신 시험분석 협업 AI`,
    "",
    "[웹앱의 목적]",
    "이 웹앱의 목적은 GPT 대화창에 시험지를 넣고 한 번에 글을 받는 것이 아니다.",
    "학교별·학년별·고사별 분석지를 누적하고, AI 1차 분석 → 강사 검수 → 문항별 코멘트 → 표/다이어그램 → 최종 산출물로 이어지는 업무 흐름을 만드는 것이다.",
    "AI는 최종 판단자가 아니라 1차 구조화 담당자다. 최종 산출물은 AI 분석과 강사 인사이트가 결합된 결과여야 한다.",
    "",
    "[입력 자료 우선순위]",
    "1. 시험지 원본/OCR에서 확인되는 사실을 최우선으로 사용한다.",
    "2. 시험관리 탭 데이터가 있으면 특이사항, 시험 범위, 부교재, 시험 일정, 시험 후 총평을 반드시 반영한다.",
    "3. 시험관리 탭 데이터가 없거나 신규 학교이면 학교·학년·과목·시험명 메타데이터와 시험지 원본만 사용한다.",
    "4. 시험관리 데이터와 시험지 원본이 충돌하면 단정하지 말고 '확인 필요'로 표시한다.",
    "5. OCR이 깨진 문자, 의미 없는 조합, 불확실한 문항번호/배점/단원명은 최종 문장에 그대로 쓰지 말고 확인 필요 항목으로 모은다.",
    "",
    "[분기 규칙]",
    "입력 자료가 1개년 기출이면 해당 시험 1회분을 깊게 분석한다.",
    "- 문항분석표, 단원별 출제, 킬러·준킬러, 변형·연계 문항, 학생 대비 전략을 우선 만든다.",
    "- 각 문항의 단원, 유형, 난이도, 역할, 태그, 출처 후보, 학생 오답 가능성, 강사 검수 포인트를 정리한다.",
    "- 배점은 해당 시험 안에서 어느 문항군이 점수에 영향을 주는지 문장으로 설명한다.",
    "",
    "입력 자료가 3개년 기출이면 연도별 변화와 반복 패턴을 우선 분석한다.",
    "- 매년 반복되는 단원, 새로 늘어난 단원, 줄어든 단원, 격년 출제 단원, 킬러 위치 변화, 서술형 변화, 부교재 반영 방식 변화를 비교한다.",
    "- 문항 수가 달라졌다면 같은 배점이라도 시험 안에서의 비중이 달라질 수 있음을 설명한다.",
    "- 별도 상대배점 차트는 만들지 않는다. 중요도 변화는 문장으로만 설명한다.",
    "- 22 개정교육과정 때문에 달라질 수 있는 부분은 '변화 가능성' 또는 '추가 확인 필요'로 구분한다.",
    "",
    "[문항별 분석 기준]",
    "시험지 첫 페이지 또는 상단의 문항 구성표를 먼저 읽고 questionComposition에 총 문항 수와 선택형/서술형 구성을 정리한다.",
    "시험지 원본이 2개 이상이면 각 원본 첫 장 기준 문항 메타데이터를 sourceCompositions에 sourceId별로 따로 정리한다.",
    "questionComposition은 문항 카드 생성 전 강사가 확인하는 초안이다. questionItems 배열 길이와 별개로 총 문항 수의 근거를 분리해서 쓴다.",
    "각 문항에 대해 가능한 범위에서 다음 항목을 정리한다.",
    "- 문항 번호",
    "- 페이지",
    "- 배점",
    "- 단원",
    "- 유형",
    "- 쎈 주유형/보조유형",
    "- 난이도",
    "- 역할",
    "- 태그",
    "- 출처 가능성",
    "- 유사문항 필요 여부",
    "- 유사문항 출처",
    "- 숫자변형/조건변형/유사유형 구분",
    "- OCR/문항 조건 요약",
    "- 학생이 틀릴 만한 지점",
    "- 강사가 확인해야 할 점",
    "- 대비 전략 후보",
    "AI 1차 분석 단계에서 문항 번호, 페이지, 배점, 쎈 기준 유형, 난이도, 단원은 웹앱 문항분석표의 questionItems 배열에 반드시 초안으로 채운다.",
    "쎈 유형은 강사가 수동 입력하기 전에 AI가 먼저 자동 매칭한다. 쎈 유형 기준표가 제공되면 문항 조건, 단원, 풀이 행동을 기준표와 비교해 questionItems.ssenTypeTags에 주유형(primary) 1개와 필요 시 보조유형(secondary) 1~2개를 typeCode/typeName/unitName/confidence/reason으로 넣는다.",
    "정확히 확정하기 어렵더라도 가장 가까운 후보를 confidence '중' 또는 '하'로 제안하고, 정말 판별 불가능한 경우에만 빈 배열로 둔다.",
    "AI가 읽은 전체 문항 수는 questionComposition.total에 넣고, 근거 문구는 questionComposition.evidence에 적는다.",
    "유사문항 본문은 웹앱에 넣지 않는다. 대신 questionItems의 similarProblemNeeded, similarProblemSource, similarProblemRelation에 메타데이터만 입력한다.",
    "유사문항 분석지나 교과서/부교재/EBS/모의고사 연계가 확인되면 숫자변형문항, 조건변형문항, 유사유형문항, 교과서 연계, 부교재 연계, EBS 연계, 모의고사 연계 태그로 기록한다.",
    "단원명/배점/난이도를 원본에서 확정할 수 없으면 빈칸으로 두지 말고 '확인 필요'로 표시한다.",
    "여러 해 시험지가 함께 들어오면 questionItems는 웹앱에서 현재 선택한 시험지/연도 1회분의 전체 문항 수만큼 작성하고, 3개년 반복/증감/변화는 텍스트 분석 필드에 정리한다.",
    "일부 페이지만 보이거나 OCR 일부만 있더라도 확인 가능한 전체 문항 수를 기준으로 questionItems를 만들고, 모르는 값은 '확인 필요'로 둔다.",
    "",
    "[문항 태그 기준]",
    "- 기본문항: 반드시 맞혀야 하는 개념 확인 문항",
    "- 실수문항: 계산, 부호, 조건 누락, 그래프 해석 등 확인할 위험이 있는 문항",
    "- 주요문항: 수업에서 반드시 다루거나 변형 관계 분석, 오답 원인 정리가 필요한 문항",
    "- 1등급 변별문항: 상위권 점수 차이를 만드는 고난도/킬러 문항",
    "- 2등급 변별문항: 중상위권을 가르는 준킬러 또는 조건 해석형 문항",
    "- 숫자변형문항/조건변형문항/유사유형문항: 유사문항 분석지에서 변형 관계가 확인된 문항",
    "- 교과서 연계/부교재 연계/EBS 연계/모의고사 연계: 출처 메타데이터가 확인된 문항",
    "",
    "[표와 다이어그램 산출 의도]",
    "AI는 웹앱에서 강사가 검수할 수 있도록 다음 표의 초안을 만든다.",
    "1. 문항분석표",
    "2. 단원별 출제표",
    "3. 쎈 유형별 분류표",
    "4. 부교재·유사문항 활용표",
    "5. 학생 대비전략표",
    "또한 대비전략 흐름은 시험 범위 확인 → 문항별 검수 → 변형 관계 분석 → 변별 문항 훈련 → 학생 수준별 보강 순서로 정리한다.",
    "",
    "[작성 원칙]",
    "- 시험지를 설명하는 데서 끝내지 말고, 학생·강사가 다음 행동을 결정할 수 있게 분석한다.",
    "- 각 항목은 가능하면 사실 근거 → 점수에 미친 영향 → 다음 학습 행동 순서로 쓴다.",
    "- '어려웠다', '중요하다', '복습이 필요하다' 같은 추상 문장으로 끝내지 않는다.",
    "- 확인되지 않은 문항번호, 배점, 단원명, 출처를 지어내지 않는다.",
    "- 부교재, 학교 프린트, 모의고사, 수능/평가원 원문항과 실제 출제 문항의 변형 관계가 보이면 반드시 표시한다.",
    "- 블로그나 인스타 초안은 AI 홍보문처럼 쓰지 말고, 학교별 시험을 실제로 본 강사의 판단이 들어갈 수 있는 구조로 쓴다.",
    "- 강사가 문항별 코멘트와 현장 체감을 추가할 수 있도록, AI 결과는 검수 가능한 초안으로 쓴다.",
    "",
    "[최종 출력 방향]",
    "1. AI 분석 결과: 시험 한 줄 총평, 시험 구조, 단원별 출제, 문항 유형, 킬러/준킬러, 변형·연계 분석, 확인 필요 항목",
    "2. 문항분석표 초안: questionItems 배열로 문항별 번호, 페이지, 배점, 단원, 유형, 쎈 유형 태그, 난이도, 역할, 태그, 출처 후보, 유사문항 메타데이터, 코멘트 후보를 반환",
    "3. 강사 인사이트 입력 가이드: 어떤 문항에 코멘트를 달아야 하는지, 어떤 문항을 크롭해서 슬라이드화하면 좋은지 제안",
    "4. 학생 대비 전략: 상위권, 중위권, 하위권으로 나누어 작성",
    "5. 재가공 핵심 메시지: 학생에게 필요한 정보, 블로그/인스타로 쓸 수 있는 정보"
  ].join("\n");
}

export function createDefaultExamAnalysis(examPrepRow = {}, options = {}) {
  const academyBrandName = options.academyBrandName || defaultAcademyBrandName;
  const getExamCycleLabel = typeof options.getExamCycleLabel === "function"
    ? options.getExamCycleLabel
    : (value) => value || "";
  const schoolName = examPrepRow.schoolName || "";
  const grade = examPrepRow.grade || "";
  const subject = examPrepRow.subject || "";
  const examName = examPrepRow.examName || (examPrepRow.examCycle ? getExamCycleLabel(examPrepRow.examCycle) : "");
  const analysisFolderId = examPrepRow.analysisFolderId || examPrepRow.folderId || createExamAnalysisFolderId({
    schoolName,
    grade,
    examName,
    examCycle: examPrepRow.examCycle || "",
    subject
  });
  const nowIso = new Date().toISOString();
  return {
    examAnalysisId: examPrepRow.examAnalysisId || `exam_analysis_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
    analysisFolderId,
    createdAt: examPrepRow.createdAt || nowIso,
    updatedAt: nowIso,
    examPrepId: examPrepRow.examPrepId || "",
    schoolName,
    grade,
    subject,
    examCycle: examPrepRow.examCycle || "",
    examName,
    examDate: "",
    sourceFileUrl: "",
    sourceFiles: [],
    sourceUploadStatus: "",
    rawExamText: "",
    questionItems: [],
    questionClassifications: [],
    questionTargetCount: 0,
    questionTargetCountsBySource: {},
    questionComposition: null,
    questionCompositionsBySource: {},
    aiProvider: "auto",
    aiModel: "server-default",
    aiStatus: "대기",
    aiLastRunAt: "",
    aiError: "",
    aiPrompt: createDefaultExamAnalysisPrompt({ academyBrandName }),
    oneLineSummary: "AI 분석을 시작하면 이번 시험의 핵심 성격이 한 문장으로 정리됩니다.",
    examStructure: "문항수, 객관식/서술형 구성, 배점, 시간 압박, 작년 대비 변화가 정리됩니다.",
    aiOverview: "시험지 원본을 넣으면 문항수, 난이도, 출제 특징이 정리됩니다.",
    unitDistribution: "단원별 문항수와 배점이 여기에 정리됩니다.",
    typeClassification: "기본/준킬러/킬러 유형과 점수 영향이 여기에 정리됩니다.",
    killerProblems: "킬러/준킬러 문항 번호, 핵심 함정, 풀이 접근이 여기에 정리됩니다.",
    fiveCorePatterns: "시험 전 확인할 5대 핵심 출제 패턴이 여기에 정리됩니다.",
    sourceCheckNotes: "OCR이 깨진 부분, 문항번호/배점 확인 필요 항목이 여기에 정리됩니다.",
    insightSummary: "이번 시험 출제 패턴 한 줄:\n작년 대비 변화:\n학생들이 가장 많이 틀린 유형:\n다음 시험 예측 한 줄:\n\n부연:",
    insightUnits: "단원명:\n출제 빈도: 매년 / 격년 / 신유형 / 감소\n학생 정답률 체감: 상 / 중 / 하\n핵심 키워드:\n\n부연:",
    insightKiller: "문항 번호 / 배점:\n출제 단원:\n유형: 기존 반복 / 신유형 / 변형\n핵심 함정 한 줄:\n\n부연:",
    insightStudentErrors: "실제 학생들이 많이 한 실수:\n계산/조건해석/개념연결 중 어디에서 무너졌는지:\n다음 수업에서 확인할 행동:\n\n부연:",
    insightPrediction: "다음 시험에 다시 나올 가능성이 높은 유형:\n줄어들 가능성이 있는 단원:\n학부모에게 설명할 예측 한 줄:\n\n부연:",
    insightDirection: "이 학교 학생들에게 가장 강조할 점:\n실수 줄이는 핵심 팁:\n누적테스트/보충에 넣을 유형:\n\n부연:",
    studentAnalysisDraft: "학생용 분석지는 A 총평 + B 단원별 인사이트 + D 학습 방향을 중심으로 생성합니다.",
    blogDraft: "블로그 초안은 학부모가 읽기 쉬운 톤으로 시험 개요, 킬러문항, 학습 방향을 연결합니다.",
    instagramDraft: `1장 표지\n2장 시험 한 줄 총평\n3장 출제 분포\n4장 킬러문항\n5장 변형·연계 분석\n6장 학습 방향\n7장 ${academyBrandName} 안내`,
    outputLayoutChoices: normalizeExamOutputLayoutChoices(),
    pipelineStage: "원본 입력"
  };
}
