import {
  getDateRangeField,
  updateDateRangeField
} from "../schoolCalendar/schoolCalendarUtils.js";
import { InlineSaveStatus } from "../../shared/components/InlineSaveStatus.jsx";
import { Modal } from "../../shared/components/Modal.jsx";
import { OverflowMenu } from "../../shared/components/OverflowMenu.jsx";

export function ExamPrepEditModal({
  getEditableMathExamEntries,
  hasChanges = false,
  isOrphaned = false,
  onAddMathExamEntry,
  onClose,
  onDeleteRow,
  onOpenReview,
  onRemoveMathExamEntry,
  onSave,
  onToggleExcluded,
  onUpdateMathExamEntry,
  onUpdateRow,
  row,
  saveState = "idle"
}) {
  const specialNote = row.specialNote ?? row.memo ?? "";
  const hasReview = Boolean(row.review || row.revisedReview);
  const isBusy = saveState === "saving" || saveState === "verifying";
  const isAutoGenerated = row.source === "학생DB 자동생성";
  // 학생DB 에서 자동 생성된 행은 연결 학생이 남아 있는 한 지워도 다음 동기화에서
  // 다시 생긴다 — 그때는 "제외" 가 맞다. 학생의 학교·학년을 고쳐서 연결이 끊긴
  // 행(연결된 활성 학생 없음)은 다시 생기지 않으므로 삭제할 수 있다(2026-09-17).
  const isDeleteBlocked = isAutoGenerated && !isOrphaned;

  // 저장하지 않은 초안이 있으면 ×·Esc·닫기 앞에서 한 번 묻는다(2026-09-19 U10 · exams-01).
  // 확인 뒤의 초안 폐기(onClose → closeExamPrepEditor)와 저장(onSave) 계약은 그대로다.
  function requestClose() {
    if (hasChanges && !window.confirm("저장하지 않은 변경이 있습니다. 닫을까요?")) return;
    onClose?.();
  }

  return (
    <Modal
      className="examPrepEditModal"
      title={`${row.schoolName || "학교 미입력"} 시험정보 수정`}
      subtitle={[row.grade, row.subject, row.publisher].filter(Boolean).join(" · ") || "시험관리 상세 입력"}
      onClose={requestClose}
      scrollable
    >
      <div className="examPrepEditForm">
        <p className="examPrepExplicitSaveNotice" role="note">
          입력 중에는 화면 초안만 바뀝니다. <strong>변경 저장</strong>을 눌러야 Supabase에 저장됩니다.
        </p>
        <section className="examPrepEditSection">
          <h2>기본 정보</h2>
          <div className="examPrepEditGrid">
            <label>
              <span>학교명</span>
              <input value={row.schoolName ?? ""} onChange={(event) => onUpdateRow(row.examPrepId, "schoolName", event.target.value)} />
            </label>
            <label>
              <span>학년</span>
              <input value={row.grade ?? ""} onChange={(event) => onUpdateRow(row.examPrepId, "grade", event.target.value)} />
            </label>
            <label>
              <span>과목</span>
              <input value={row.subject ?? ""} onChange={(event) => onUpdateRow(row.examPrepId, "subject", event.target.value)} />
            </label>
            <label>
              <span>출판사</span>
              <input value={row.publisher ?? ""} onChange={(event) => onUpdateRow(row.examPrepId, "publisher", event.target.value)} />
            </label>
          </div>
        </section>

        <section className="examPrepEditSection">
          <h2>시험 일정</h2>
          <div className="examPrepDateGrid examDateRangeInputs">
            <label>
              <span>시험기간 시작일</span>
              <input
                type="date"
                value={getDateRangeField(row.examPeriod, "date")}
                onChange={(event) =>
                  onUpdateRow(row.examPrepId, "examPeriod", updateDateRangeField(row.examPeriod, "date", event.target.value))
                }
              />
            </label>
            <label>
              <span>시험기간 종료일</span>
              <input
                type="date"
                value={getDateRangeField(row.examPeriod, "endDate")}
                onChange={(event) =>
                  onUpdateRow(row.examPrepId, "examPeriod", updateDateRangeField(row.examPeriod, "endDate", event.target.value))
                }
              />
            </label>
          </div>
          {/* 리피터 행 순서·라벨·추가 버튼은 학사일정 등록 모달의 '수학시험 날짜' 리피터와 맞춘다(exams-22 1단계).
              행이 하나뿐일 때는 × 를 렌더하지 않는다 — 지워도 빈 행이 다시 채워지므로 값 비우기와 같다(2026-09-19 U9). */}
          <div className="mathExamEntryEditor modalMathExamEntryEditor">
            {getEditableMathExamEntries(row).map((entry, entryIndex, entries) => (
              <div className="mathExamEntryRow" key={entry.id || entryIndex}>
                <label>
                  <span>수학시험 날짜</span>
                  <input
                    type="date"
                    value={entry.date ?? ""}
                    onChange={(event) => onUpdateMathExamEntry(row, entryIndex, "date", event.target.value)}
                  />
                </label>
                <label>
                  <span>학년</span>
                  <input
                    value={entry.grade ?? ""}
                    placeholder="예: 고3"
                    onChange={(event) => onUpdateMathExamEntry(row, entryIndex, "grade", event.target.value)}
                  />
                </label>
                <label>
                  <span>과목</span>
                  <input
                    value={entry.subject ?? ""}
                    placeholder="예: 미적분"
                    onChange={(event) => onUpdateMathExamEntry(row, entryIndex, "subject", event.target.value)}
                  />
                </label>
                <label>
                  <span>표시명</span>
                  <input
                    value={entry.label ?? ""}
                    placeholder="표시명 선택"
                    onChange={(event) => onUpdateMathExamEntry(row, entryIndex, "label", event.target.value)}
                  />
                </label>
                {entries.length > 1 ? (
                  <button
                    aria-label={`${entryIndex + 1}번째 수학시험 제거`}
                    className="iconButton"
                    onClick={() => onRemoveMathExamEntry(row, entryIndex)}
                    type="button"
                  >
                    ×
                  </button>
                ) : null}
              </div>
            ))}
            <button className="softButton compact" type="button" onClick={() => onAddMathExamEntry(row)}>
              + 수학시험 추가
            </button>
          </div>
        </section>

        <section className="examPrepEditSection">
          <h2>시험 내용</h2>
          <div className="examPrepTextareaGrid">
            <label>
              <span>특이사항</span>
              <textarea
                value={specialNote}
                onChange={(event) => onUpdateRow(row.examPrepId, "specialNote", event.target.value)}
                placeholder="학교별 특이사항"
              />
            </label>
            <label>
              <span>시험 범위</span>
              <textarea value={row.scope ?? ""} onChange={(event) => onUpdateRow(row.examPrepId, "scope", event.target.value)} />
            </label>
            <label>
              <span>부교재</span>
              <textarea value={row.subTextbook ?? ""} onChange={(event) => onUpdateRow(row.examPrepId, "subTextbook", event.target.value)} />
            </label>
          </div>
        </section>

        <div className="examPrepEditActionFooter">
          {saveState !== "idle" ? (
            <div aria-label="시험정보 저장 상태" className="examPrepEditStatusBar" role="group">
              <InlineSaveStatus label="시험정보" saveState={saveState} />
            </div>
          ) : null}
          <div className="examPrepEditActionRow">
            <div aria-label="이 시험정보에 대한 작업" className="examPrepEditRowActions" role="group">
              {/* 파괴적 액션(삭제)은 왼쪽 끝 ⋯ 메뉴로 접고, 삭제할 수 없는 자동생성 행은 비활성 버튼 대신
                  이유를 바로 보여준다. 확인·감사 흐름은 onDeleteRow(App.jsx) 가 그대로 맡는다(2026-09-19). */}
              {isDeleteBlocked ? (
                <small className="muted examPrepEditDeleteNote" role="note">
                  연결된 학생이 있는 동안은 삭제해도 다시 생성됩니다. 이번 고사에서 빼려면 "내신 준비 제외" 를 쓰세요.
                </small>
              ) : (
                <OverflowMenu
                  className="overflowMenu-start"
                  items={isBusy ? [] : [{ key: "delete", label: "시험정보 삭제", onSelect: () => onDeleteRow?.(row.examPrepId), tone: "danger" }]}
                  label={`${row.schoolName || "학교 미입력"} 추가 작업`}
                  placement="top"
                />
              )}
              {/* 제외/포함은 초안만 바꾸는 되돌릴 수 있는 토글이라 위험 톤이 아니라 softButton 이다. */}
              <button className="softButton" disabled={isBusy} onClick={onToggleExcluded} type="button">
                {row.isExcluded ? "시험관리 다시 포함" : "이번 고사 내신 준비 제외"}
              </button>
              <button className="softButton" disabled={isBusy || hasChanges} onClick={onOpenReview} type="button">
                {hasReview ? "시험 후 총평 보기/수정" : "시험 후 총평 작성"}
              </button>
            </div>
            <div aria-label="모달 처리" className="examPrepEditModalActions" role="group">
              <button className="softButton" disabled={isBusy} onClick={requestClose} type="button">닫기</button>
              <button className="primaryButton" disabled={isBusy || !hasChanges} onClick={onSave} type="button">
                {isBusy ? "저장 중" : "변경 저장"}
              </button>
            </div>
          </div>
        </div>
      </div>
    </Modal>
  );
}
