// 쎈 목차 중단원 목록. api/data/ssenTypeIndex.json 에서 중단원 단위로 추출한 정적 데이터.
// 재생성: node scripts/build-ssen-unit-catalog.mjs
// 시험지 라이브러리(단원별 평가) 전용. 이 파일만으로 예정 시험지 카탈로그를 만들 수 있어
// App.jsx / main 청크에 의존하지 않는다.

export const SSEN_UNIT_ROWS = [
  { subject: "공통수학1", unitNo: "01", unitName: "다항식의 연산", partName: "다항식" },
  { subject: "공통수학1", unitNo: "02", unitName: "나머지 정리와 인수분해", partName: "다항식" },
  { subject: "공통수학1", unitNo: "03", unitName: "복소수", partName: "방정식" },
  { subject: "공통수학1", unitNo: "04", unitName: "이차방정식", partName: "방정식" },
  { subject: "공통수학1", unitNo: "05", unitName: "이차방정식과 이차함수", partName: "방정식" },
  { subject: "공통수학1", unitNo: "06", unitName: "여러 가지 방정식", partName: "방정식" },
  { subject: "공통수학1", unitNo: "07", unitName: "일차부등식", partName: "부등식" },
  { subject: "공통수학1", unitNo: "08", unitName: "이차부등식", partName: "부등식" },
  { subject: "공통수학1", unitNo: "09", unitName: "순열과 조합", partName: "순열과 조합" },
  { subject: "공통수학1", unitNo: "10", unitName: "행렬과 그 연산", partName: "행렬" },
  { subject: "공통수학2", unitNo: "01", unitName: "평면좌표", partName: "도형의 방정식" },
  { subject: "공통수학2", unitNo: "02", unitName: "직선의 방정식", partName: "도형의 방정식" },
  { subject: "공통수학2", unitNo: "03", unitName: "원의 방정식", partName: "도형의 방정식" },
  { subject: "공통수학2", unitNo: "04", unitName: "도형의 이동", partName: "도형의 방정식" },
  { subject: "공통수학2", unitNo: "05", unitName: "집합의 뜻과 표현", partName: "집합과 명제" },
  { subject: "공통수학2", unitNo: "06", unitName: "집합의 연산", partName: "집합과 명제" },
  { subject: "공통수학2", unitNo: "07", unitName: "명제", partName: "집합과 명제" },
  { subject: "공통수학2", unitNo: "08", unitName: "함수", partName: "함수" },
  { subject: "공통수학2", unitNo: "09", unitName: "유리식과 유리함수", partName: "함수" },
  { subject: "공통수학2", unitNo: "10", unitName: "무리식과 무리함수", partName: "함수" },
  { subject: "기하", unitNo: "01", unitName: "이차곡선", partName: "이차곡선" },
  { subject: "기하", unitNo: "02", unitName: "이차곡선과 직선", partName: "이차곡선" },
  { subject: "기하", unitNo: "03", unitName: "벡터의 연산", partName: "벡터" },
  { subject: "기하", unitNo: "04", unitName: "평면벡터의 성분과 내적", partName: "벡터" },
  { subject: "기하", unitNo: "05", unitName: "공간도형", partName: "공간도형" },
  { subject: "기하", unitNo: "06", unitName: "공간좌표", partName: "공간도형" },
  { subject: "대수", unitNo: "01", unitName: "지수", partName: "지수함수와 로그함수" },
  { subject: "대수", unitNo: "02", unitName: "로그", partName: "지수함수와 로그함수" },
  { subject: "대수", unitNo: "03", unitName: "지수함수", partName: "지수함수와 로그함수" },
  { subject: "대수", unitNo: "04", unitName: "로그함수", partName: "지수함수와 로그함수" },
  { subject: "대수", unitNo: "05", unitName: "삼각함수", partName: "삼각함수" },
  { subject: "대수", unitNo: "06", unitName: "삼각함수의 그래프", partName: "삼각함수" },
  { subject: "대수", unitNo: "07", unitName: "삼각함수의 활용", partName: "삼각함수" },
  { subject: "대수", unitNo: "08", unitName: "등차수열과 등비수열", partName: "수열" },
  { subject: "대수", unitNo: "09", unitName: "수열의 합", partName: "수열" },
  { subject: "대수", unitNo: "10", unitName: "수학적 귀납법", partName: "수열" },
  { subject: "미적분1", unitNo: "01", unitName: "함수의 극한", partName: "함수의 극한과 연속" },
  { subject: "미적분1", unitNo: "02", unitName: "함수의 연속", partName: "함수의 극한과 연속" },
  { subject: "미적분1", unitNo: "03", unitName: "미분계수와 도함수", partName: "다항함수의 미분법" },
  { subject: "미적분1", unitNo: "04", unitName: "도함수의 활용 (1)", partName: "다항함수의 미분법" },
  { subject: "미적분1", unitNo: "05", unitName: "도함수의 활용 (2)", partName: "다항함수의 미분법" },
  { subject: "미적분1", unitNo: "06", unitName: "도함수의 활용 (3)", partName: "다항함수의 미분법" },
  { subject: "미적분1", unitNo: "07", unitName: "부정적분", partName: "다항함수의 적분법" },
  { subject: "미적분1", unitNo: "08", unitName: "정적분", partName: "다항함수의 적분법" },
  { subject: "미적분1", unitNo: "09", unitName: "정적분의 활용", partName: "다항함수의 적분법" },
  { subject: "확률과 통계", unitNo: "01", unitName: "여러 가지 순열", partName: "경우의 수" },
  { subject: "확률과 통계", unitNo: "02", unitName: "중복조합과 이항정리", partName: "경우의 수" },
  { subject: "확률과 통계", unitNo: "03", unitName: "확률의 뜻과 활용", partName: "확률" },
  { subject: "확률과 통계", unitNo: "04", unitName: "조건부확률", partName: "확률" },
  { subject: "확률과 통계", unitNo: "05", unitName: "확률변수와 확률분포", partName: "통계" },
  { subject: "확률과 통계", unitNo: "06", unitName: "이항분포와 정규분포", partName: "통계" },
  { subject: "확률과 통계", unitNo: "07", unitName: "통계적 추정", partName: "통계" }
];
