export function selectAutoGeneratedDisplayLessons(planItems = []) {
  return planItems
    .filter(
      (item) =>
        item.lesson?.lessonType !== "preExam" &&
        (item.status === "create" || item.status === "update")
    )
    .map((item) => ({
      ...item.lesson,
      isExamPrepAutoLesson: true,
      isVirtualGeneratedLesson: item.status === "create",
      generatedKey: item.generatedKey
    }));
}
