export function mergeGeneratedCalendarLessons({
  autoGeneratedDisplayLessons = [],
  getIdentityKeys = () => [],
  isLegacyLesson = () => false,
  lessons = []
} = {}) {
  const autoDisplayKeys = new Set(
    autoGeneratedDisplayLessons.flatMap(getIdentityKeys)
  );
  const baseLessons = lessons.filter(
    (lesson) =>
      !isLegacyLesson(lesson) &&
      !getIdentityKeys(lesson).some((key) => autoDisplayKeys.has(key))
  );
  return [...baseLessons, ...autoGeneratedDisplayLessons];
}
